#!/bin/bash

#Try to install everything that pacman can find
sudo pacman -S --needed $(comm -12 <(pacman -Slq | sort) <(sort package_list.txt))

#Leftover AURs isntall with yay
sudo pacman -S --needed - < package_list.txt
